---
- hosts: all
  tasks:
    - name: Install dependencies from snap
      community.general.snap:
        name:
          - sccache
        channel: candidate
        classic: true
    - name: Install dependencies from apt
      ansible.builtin.apt:
        package:
          - build-essential
          - clang
          - cmake
          - git
          - icu-devtools
          - libcurl4-openssl-dev
          - libedit-dev
          - libicu-dev
          - libncurses5-dev
          - libpython3-dev
          - libsqlite3-dev
          - libxml2-dev
          - ninja-build
          - pkg-config
          - python
          - python-six
          - python2-dev
          - python3-six
          - python3-distutils
          - rsync
          - swig
          - systemtap-sdt-dev
          - tzdata
          - unzip
          - uuid-dev
        state: present

