---
- hosts: all
  tasks:
    - name: Create a buildbot user
      ansible.builtin.user:
        name: buildbot
        shell: /bin/bash
      become: true

    - name: Set authorized keys for buildbot
      ansible.posix.authorized_key:
        user: buildbot
        state: present
        key: '{{ item }}'
      become: true
      with_file:
        - public-keys/apple-jenkins.pub
        - public-keys/katei.pub

    - name: Install dependencies from snap
      community.general.snap:
        name:
          - sccache
        channel: candidate
        classic: true
      become: true
    - name: Install dependencies from apt
      ansible.builtin.apt:
        package:
          - build-essential
          - clang
          - cmake
          - git
          - icu-devtools
          - libcurl4-openssl-dev
          - libedit-dev
          - libicu-dev
          - libncurses5-dev
          - libpython3-dev
          - libsqlite3-dev
          - libxml2-dev
          - ninja-build
          - pkg-config
          - python
          - python-six
          - python2-dev
          - python3-six
          - python3-distutils
          - rsync
          - swig
          - systemtap-sdt-dev
          - tzdata
          - unzip
          - uuid-dev
          - default-jre # so the Jenkins master can access the server
        state: present
      become: true

